export const STUDENT_ACTION_RULES = Object.freeze({
  saveCaffeineData: 'identityPayload',
  getCaffeineLogs: 'identityFirst',
  deleteCaffeineData: 'ownership',
  updateCaffeineData: 'identityPayload',
  saveSleepData: 'identityPayload',
  getSleepLogs: 'identityFirst',
  deleteSleepData: 'ownership',
  updateSleepData: 'identityPayload',
  getWeightData: 'identityFirst',
  saveInitialSetup: 'identityPayload',
  getStats: 'identityFirst',
  getStudentBootstrap: 'identityFirst',
  getFilteredStats: 'identityFirst',
  getTeacherAwardsForStudent: 'identityFirst',
  markTeacherAwardsSeen: 'identityPair',
  submitInquiry: 'identityPayload',
  getMyInquiries: 'identityFirst',
  markInquiryRepliesSeen: 'identityPair',
  getCaffeineDB: 'passthrough',
  testConnection: 'passthrough',
  generateAIHealthReport: 'identityPair',
  analyzeDrinkImageWithAI: 'passthrough',
  getTeacherMessages: 'identityFirst',
  markTeacherMessageRead: 'ownership',
  replyToTeacherMessage: 'ownership',
  getBadgeConfig: 'passthrough',
  getChallengeBadgeConfig: 'passthrough',
  getSleepSettings: 'passthrough',
  savePushSubscription: 'pushSubscription',
  getPushPreferences: 'subscriptionOwned',
  savePushPreferences: 'subscriptionOwned',
  deactivatePushSubscription: 'subscriptionOwned',
  getReminderStudentConfig: 'passthrough',
});

export const STUDENT_ACTIONS = new Set(Object.keys(STUDENT_ACTION_RULES));
